export const LOGIN = '/login'
export const CREATE_ACCOUNT = '/create-account'

export const PROFILE = '/profile'
export const DASHBOARD = '/dashboard'
export const FRIENDS = '/friends'
export const CREATE_MATCH = '/create-match'
export const EDIT_MATCH = '/edit-match/:id'
export const MATCHES = '/matches'
export const MATCH_DETAILS = '/match/:id'
