Table user {
  id INTEGER [pk, increment]
  email TEXT [not null]
  firstName TEXT [not null]
  middleAndSurname TEXT [not null]
  age INTEGER [not null]
  password TEXT [not null]
  addressId INTEGER
  unregisteredAt DATETIME
}
Ref: user.addressId > address.id [delete: no action, update: no action]

Table anonFriend {
  id INTEGER [pk, increment]
  userId INTEGER [not null]
  fullName TEXT
}
Ref: anonFriend.userId > user.id [delete: cascade, update: no action]

Table match {
  id INTEGER [pk, increment]
  authorId INTEGER [not null]
  // boardgameId TEXT // FUTURE
  boardgameName TEXT [not null]
  startedAt STRING
  endedAt STRING
  duration INTEGER [note: 'Match duration in seconds']
  notes TEXT
  deleted_at STRING

  Indexes {
    authorId
  }
}
Ref: match.authorId > user.id [delete: no action, update: no action]

Table matchParticipant {
  matchId INTEGER [not null]
  userId INTEGER
  anonFriendId INTEGER
  score INTEGER
  // notes TEXT

  Indexes {
    matchId
    (matchId, userId, anonFriendId) [pk]
  }
  // TODO: add constraint to require either a userId or an anonFriendId
  // CONSTRAINT user_or_anon_friend
  // check (
  //   (userId IS NOT NULL AND anonFriendId IS NULL)
  //   OR (userId IS NULL AND anonFriendId IS NOT NULL)
  // )
}
Ref: matchParticipant.matchId > match.id [delete: cascade, update: no action]
Ref: matchParticipant.userId > user.id [delete: cascade, update: no action]
Ref: matchParticipant.anonFriendId > anonFriend.id [delete: cascade, update: no action]


// --------------
// For the future
// --------------

Table friendship {
  userAId INTEGER
  userBId INTEGER

  Indexes {
    (userAId, userBId) [pk]
  }
}
Ref: friendship.userAId > user.id [delete: cascade, update: no action]
Ref: friendship.userBId > user.id [delete: cascade, update: no action]

Table friendshipRequest {
  requestingUserId INTEGER
  requestedUserId INTEGER

  Indexes {
    (requestingUserId, requestedUserId) [pk]
  }
}
Ref: friendshipRequest.requestingUserId > user.id [delete: cascade, update: no action]
Ref: friendshipRequest.requestedUserId > user.id [delete: cascade, update: no action]

Table address {
  id INTEGER [pk, increment] // auto-increment
  country TEXT [not null]
  state TEXT [not null]
  city TEXT [not null]
  address TEXT [not null]
  postalCode TEXT [not null]
}

Table favoriteBG {
  userId INTEGER [not null]
  boardgameId TEXT [not null]

  Indexes {
    userId
    (boardgameId, userId) [pk]
  }
}
Ref: favoriteBG.userId > user.id [delete: cascade, update: no action]

Table wishedBG {
  userId INTEGER [not null]
  boardgameId TEXT [not null]

  Indexes {
    userId
    (boardgameId, userId) [pk]
  }
}
Ref: wishedBG.userId > user.id [delete: cascade, update: no action]

Table toTradeBG {
  userId INTEGER [not null]
  boardgameId TEXT [not null]

  Indexes {
    userId
    (boardgameId, userId) [pk]
  }
}
Ref: toTradeBG.userId > user.id [delete: cascade, update: no action]
